version: '3.9'


services: 
  nginx:
    container_name: tv-maze-app
    restart: always
    build: 
      context: .
      dockerfile: nginx/Dockerfile      
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/usr/share/nginx/html
    
    networks:
      - mynetwork

networks: 
  mynetwork:
